Update archive-project-artifacts

diff --git a/bin/archive-project-artifacts b/bin/archive-project-artifacts
--- a/bin/archive-project-artifacts
+++ b/bin/archive-project-artifacts
@@ -1,8 +1,12 @@
 #!/usr/bin/env bash
 
 archive_artifacts() {
-  local project_root="${1:-.}"; shift
-  test "$project_root" = '.' && project_root="$(pwd)"
+  local project_root="$(readlink -f "${1:-.}")"; shift
+  local archive_target; archive_target="$(readlink -f "${1:-.}")" || {
+    echo "Invalid path: '$1'"
+    return 1;
+  }
+  shift
 
   adir="$(mktemp -d --tmpdir "$JOB_NAME".XXXXXXX)"
   test -d "$adir" || return 1
@@ -11,7 +15,7 @@ archive_artifacts() {
     --exclude-vcs-ignores --exclude-vcs \
     --exclude-backups --exclude-caches \
     -C "$project_root" . && \
-  mv "$adir"/app.tgz . && \
+  mv "$adir"/app.tgz "$archive_target" && \
   rm -rf "$adir" || \
   { rm -rf "$adir"; return 1 ;}
 
