Fix find's 'starting-points' argument (it should end in '/') and exit status handling

diff --git a/bin/dockerize-project b/bin/dockerize-project
--- a/bin/dockerize-project
+++ b/bin/dockerize-project
@@ -58,17 +58,17 @@ generate_dockerfile_and_archive() {
   test "$ptype" = jvm && {
     dockerfile_dir="$project_root"/target
     local gradle_dist
-    gradle_dist="$(find "$project_root"/build/distributions -name '*.tar')" && \
-      ptype=jvm:gradle
+    gradle_dist="$(find "$project_root"/build/distributions/ -name '*.tar')"
+    test "$gradle_dist" && ptype=jvm:gradle
   }
   case "$ptype" in
     jvm:gradle)
       tar_params+=(.); all_included=T
       local app_exec
       tar --strip-components=1 -xf "$gradle_dist" -C "$dockerfile_dir" || return
-      app_exec="$(find "$dockerfile_dir"/bin -mindepth 1 ! -type d ! -name '*.*')" && test -x "$app_exec" || {
-        echo "Unable to find Gradle-generated executable at '"$dockerfile_dir"/bin':"
-        find "$dockerfile_dir"/bin -mindepth 1 ! -type d ! -name '*.*' -exec ls -lhFa {} +
+      app_exec="$(find "$dockerfile_dir"/bin/ -mindepth 1 ! -type d ! -name '*.*')" && test -x "$app_exec" || {
+        echo "Unable to find Gradle-generated executable at '"$dockerfile_dir"/bin/':"
+        find "$dockerfile_dir"/bin/ -mindepth 1 ! -type d ! -name '*.*' -exec ls -lhFa {} +
         return 1
       }
       ;;
